'use strict';
const Localization=(()=>{
  const commonEn={
    section:'Section',currency:'Currency',scenario:'Scenario',create:'Create',duplicate:'Duplicate',rename:'Rename',delete:'Delete',undo:'Undo',redo:'Redo',reset:'Reset to Default',advancedSettings:'Advanced Settings',basicSettings:'Basic Settings',exportPdf:'Export PDF',exportExcel:'Export Excel',
    title:'FINANCIAL MODEL — BRAZIL',subtitle:'12-Month Projection',cashFlowOverview:'CASH FLOW OVERVIEW',chartSubtitle:'Monthly partner net profit and accumulated result',keyInsights:'KEY INSIGHTS',summary12:'SUMMARY (12 MONTHS)',inputsAssumptions:'INPUTS (ASSUMPTIONS)',legend:'LEGEND',notes:'NOTES',
    initialInvestment:'TOTAL INVESTMENT (12 MONTHS)',breakEven:'BREAK-EVEN',yearProfit:'YEAR 1 PROFIT',roi12:'ROI (12 MONTHS)',month:'Month',setup:'Setup',setupPreparation:'Setup / Preparation',preparation:'Preparation',preOpening:'PRE-OPENING',growthPhase:'GROWTH PHASE',
    investment:'INVESTMENT',operations:'ORDER VOLUME FORECAST',orderIndicators:'ORDER VOLUME FORECAST',revenueDistribution:'REVENUE DISTRIBUTION',operatingExpenses:'OPERATING EXPENSES',profitCash:'PARTNER PROFIT FORECAST',
    initialPurchase:'License Fee',marketingInvestment:'Marketing & Advertising Investment',totalInvestment:'Total Investment',ridesPerDay:'Rides per Day',ridesPerMonth:'Rides per Month',averageFare:'Average Ride Price, BRL',grossRideValue:'Gross Ride Value (BRL)',
    maximShare:'Technology Use Fee Share (%)',maximRevenue:'Technology Use Fee Revenue (BRL)',partnerShare:'Partner Share (%)',partnerRevenue:'Partner Revenue (BRL)',marketingAdvertising:'Marketing & Advertising',operationsAdmin:'Operations & Admin',otherCosts:'Other Costs',assistente:'Assistant',totalOperatingExpenses:'Total Operating Expenses',
    netProfit:'Net Profit (BRL)',netProfitMargin:'Net Profit Margin (%)',netCashFlow:'Net Cash Flow (BRL)',accumulatedCashFlow:'Accumulated Net Profit (BRL)',population:'Population',commission:'Commission from Completed Rides (%)',rideGrowth:'Ride Growth',percentagePopulationUsingService:'Population Using Service (%)',marketingBudget:'Marketing Budget',initialInvestmentInput:'Initial Investment',operatingExpensesInput:'Operating Expenses',
    marketingDistributionPreset:'Marketing Budget Allocation',ridesDistributionPreset:'Monthly Order Ramp-up',presetHint:'Preset fills months 1–12. Manual edits in the table are stored as percentages while cells show rounded absolute values.',
    investmentLegend:'Investment',operationsLegend:'Order Volume Forecast',revenueLegend:'Revenue Distribution',expensesLegend:'Partner Expenses',profitLegend:'Partner Profit',breakEvenMonth:'Break-even Month',strongGrowth:'Strong Growth',highProfitability:'High Profitability',positiveCashFlow:'Positive Cash Flow',
    breakEvenText:'Business becomes profitable in {month}.',strongGrowthText:'Revenue grows steadily across the projection.',profitText:'Year 1 Net Profit: {profit} with {roi} ROI.',cashText:'Positive accumulated cash flow from {month} onwards.',
    totalRevenuePartner:'Partner Revenue',totalPartnerRevenue:'Partner Revenue',totalCommissionFromRides:'Commission from Completed Rides',paybackPeriod:'Payback Period',allValues:'All values in BRL. Figures are illustrative and may vary based on market conditions.',
    confirmReset:'Reset current scenario to default values?',confirmDelete:'Delete this scenario?',nameScenario:'Scenario name',validationPopulation:'Population must be greater than 0.',validationPopulationUsing:'Population using service must be between 1% and 4%.',validationFare:'Average ride price must be greater than 0.',validationCommission:'Commission must be between 0 and 50%.',validationGrowth:'Ride growth must be between -90% and 200%.',validationMarketing:'Marketing budget cannot be negative.',validationInvestment:'Initial investment cannot be negative.',validationExpenses:'Operating expenses cannot be negative.',
    averageRidePrice:'Average Ride Price, BRL',commissionFromCompletedRidesPct:'Commission from Completed Rides (%)',commissionFromCompletedRidesValue:'Commission from Completed Rides (BRL)',feeFrom:'Fee from',revenueDistributionRules:'Revenue distribution rules',revenueRulesHint:'Monthly commission is compared with Brazilian thresholds. The matching percentage is the technology use fee; the rest remains with the partner.',
    addRow:'+ Add row',addRule:'+ Add rule',show:'Show',brl:'BRL',monthlyNetProfit:'Monthly Net Profit',accumulatedNetProfit:'Accumulated Net Profit',intersectionPoint:'Intersection point',welcomeTitle:'Select a city to calculate the financial model',welcomeSubtitle:'Choose a Brazilian state and city from the available list. Population and initial payment will be applied automatically.',state:'State',city:'City',selectState:'Select state',selectCity:'Select city',calculate:'Calculate',availableCities:'Available cities',initialPayment:'Initial Payment',selectedCity:'Selected city',changeCity:'Change city',cityHeader:'City',populationHeader:'Population',initialPaymentHeader:'Initial Payment'
  };
  const pt={
    section:'Seção',currency:'Moeda',scenario:'Cenário',create:'Criar',duplicate:'Duplicar',rename:'Renomear',delete:'Excluir',undo:'Desfazer',redo:'Refazer',reset:'Restaurar padrão',advancedSettings:'Configurações avançadas',basicSettings:'Configurações básicas',exportPdf:'Exportar PDF',exportExcel:'Exportar Excel',
    title:'MODELO FINANCEIRO — BRASIL',subtitle:'Projeção de 12 meses',cashFlowOverview:'VISÃO GERAL DO FLUXO DE CAIXA',chartSubtitle:'Lucro líquido mensal do parceiro e resultado acumulado',keyInsights:'PRINCIPAIS INSIGHTS',summary12:'RESUMO (12 MESES)',inputsAssumptions:'ENTRADAS (PREMISSAS)',legend:'LEGENDA',notes:'NOTAS',
    initialInvestment:'INVESTIMENTO TOTAL (12 MESES)',breakEven:'PONTO DE EQUILÍBRIO',yearProfit:'LUCRO DO ANO 1',roi12:'ROI (12 MESES)',month:'Mês',setup:'Setup',setupPreparation:'Setup / Preparação',preparation:'Preparação',preOpening:'PRÉ-ABERTURA',growthPhase:'FASE DE CRESCIMENTO',
    investment:'INVESTIMENTO',operations:'PREVISÃO DE VOLUME DE PEDIDOS',orderIndicators:'PREVISÃO DE VOLUME DE PEDIDOS',revenueDistribution:'DISTRIBUIÇÃO DE RECEITA',operatingExpenses:'DESPESAS OPERACIONAIS',profitCash:'PREVISÃO DE LUCRO DO PARCEIRO',
    initialPurchase:'Taxa de licença',marketingInvestment:'Investimento em marketing e publicidade',totalInvestment:'Investimento total',ridesPerDay:'Pedidos por dia',ridesPerMonth:'Pedidos por mês',averageFare:'Preço médio da corrida, R$',grossRideValue:'Valor bruto das corridas (R$)',
    maximShare:'Porcentagem da taxa de uso de tecnologia',maximRevenue:'Taxa de uso de tecnologia em R$',partnerShare:'Percentual do parceiro (%)',partnerRevenue:'Receita do parceiro (R$)',marketingAdvertising:'Marketing e publicidade',operationsAdmin:'Operações e administração',otherCosts:'Outros custos',assistente:'Assistente',totalOperatingExpenses:'Total de despesas operacionais',
    netProfit:'Lucro líquido (R$)',netProfitMargin:'Margem de lucro líquido (%)',netCashFlow:'Fluxo de caixa líquido (R$)',accumulatedCashFlow:'Lucro líquido acumulado (R$)',population:'População',commission:'Comissão sobre corridas concluídas (%)',rideGrowth:'Crescimento de corridas',percentagePopulationUsingService:'População que usa o serviço (%)',marketingBudget:'Orçamento de marketing',initialInvestmentInput:'Investimento inicial',operatingExpensesInput:'Despesas operacionais',
    marketingDistributionPreset:'Distribuição do orçamento de marketing',ridesDistributionPreset:'Crescimento mensal de pedidos',presetHint:'O preset preenche os meses 1–12. Edições manuais na tabela são armazenadas em porcentagem, mas as células exibem valores absolutos arredondados.',
    investmentLegend:'Investimento',operationsLegend:'Previsão de pedidos',revenueLegend:'Distribuição de receita',expensesLegend:'Despesas do parceiro',profitLegend:'Lucro do parceiro',breakEvenMonth:'Mês de equilíbrio',strongGrowth:'Crescimento forte',highProfitability:'Alta rentabilidade',positiveCashFlow:'Fluxo de caixa positivo',
    breakEvenText:'O negócio atinge o ponto de equilíbrio em {month}.',strongGrowthText:'A receita cresce de forma consistente durante a projeção.',profitText:'Lucro líquido do ano 1: {profit} com ROI de {roi}.',cashText:'Fluxo de caixa acumulado positivo a partir de {month}.',
    totalRevenuePartner:'Receita do parceiro',totalPartnerRevenue:'Receita do parceiro',totalCommissionFromRides:'Comissão sobre corridas concluídas',paybackPeriod:'Prazo de retorno',allValues:'Todos os valores em BRL. Os números são ilustrativos e podem variar conforme as condições de mercado.',
    confirmReset:'Restaurar este cenário para os valores padrão?',confirmDelete:'Excluir este cenário?',nameScenario:'Nome do cenário',validationPopulation:'A população deve ser maior que 0.',validationPopulationUsing:'A população que usa o serviço deve estar entre 1% e 4%.',validationFare:'O preço médio da corrida deve ser maior que 0.',validationCommission:'A comissão deve estar entre 0 e 50%.',validationGrowth:'O crescimento de corridas deve estar entre -90% e 200%.',validationMarketing:'O orçamento de marketing não pode ser negativo.',validationInvestment:'O investimento inicial não pode ser negativo.',validationExpenses:'As despesas operacionais não podem ser negativas.',
    averageRidePrice:'Preço médio da corrida, R$',commissionFromCompletedRidesPct:'Comissão sobre corridas concluídas (%)',commissionFromCompletedRidesValue:'Comissão sobre corridas concluídas (R$)',feeFrom:'A partir de',revenueDistributionRules:'Regras de distribuição de receita',revenueRulesHint:'A comissão mensal é comparada com as faixas do Brasil. A porcentagem correspondente vira taxa de uso de tecnologia; o restante fica com o parceiro.',
    addRow:'+ Adicionar linha',addRule:'+ Adicionar regra',show:'Mostrar',brl:'BRL',monthlyNetProfit:'Lucro líquido mensal',accumulatedNetProfit:'Lucro líquido acumulado',intersectionPoint:'Ponto de interseção',welcomeTitle:'Selecione uma cidade para calcular o modelo financeiro',welcomeSubtitle:'Escolha um estado e uma cidade do Brasil. A população e o pagamento inicial serão aplicados automaticamente.',state:'Estado',city:'Cidade',selectState:'Selecionar estado',selectCity:'Selecionar cidade',calculate:'Calcular',availableCities:'Cidades disponíveis',initialPayment:'Pagamento inicial',selectedCity:'Cidade selecionada',changeCity:'Alterar cidade',cityHeader:'Cidade',populationHeader:'População',initialPaymentHeader:'Pagamento inicial'
  };
  const dict={'pt-BR':pt,en:commonEn};
  let lang='pt-BR';
  function t(k,v={}){let s=(dict[lang]&&dict[lang][k])||dict.en[k]||k;Object.keys(v).forEach(x=>s=s.replaceAll('{'+x+'}',v[x]));return s}
  function setLanguage(l){lang=dict[l]?l:'pt-BR';document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));}
  return{t,setLanguage,getLanguage:()=>lang,languages:Object.keys(dict)}
})();
